#!/usr/bin/env node
/**
 * Syncs PROTEGO design tokens into packages/ui.
 *
 * Source of truth (design handoff, not to be edited by hand):
 *   design/PROTEGO mobile safety system design/design/tokens.json
 *   design/PROTEGO mobile safety system design/design/tokens.css
 *
 * Outputs (generated, not to be edited by hand):
 *   packages/ui/src/tokens.ts   — resolved token object for React Native / TS consumers
 *   packages/ui/src/tokens.css  — CSS custom properties for the web (Next.js/Tailwind)
 *
 * Run: pnpm --filter @protego/ui run tokens:sync
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "../../..");

const DESIGN_DIR = path.join(
  repoRoot,
  "design",
  "PROTEGO mobile safety system design",
  "design"
);
const TOKENS_JSON_SRC = path.join(DESIGN_DIR, "tokens.json");
const TOKENS_CSS_SRC = path.join(DESIGN_DIR, "tokens.css");

const OUT_DIR = path.join(__dirname, "..", "src");
const TOKENS_TS_OUT = path.join(OUT_DIR, "tokens.ts");
const TOKENS_CSS_OUT = path.join(OUT_DIR, "tokens.css");

const GENERATED_HEADER = `// AUTO-GENERATED by packages/ui/scripts/sync-tokens.mjs — do not edit by hand.
// Source: design/PROTEGO mobile safety system design/design/tokens.json
// Regenerate: pnpm --filter @protego/ui run tokens:sync
`;

/** Resolve "{color.base.gold}"-style references against the root token tree. */
function resolveRefs(node, root) {
  if (typeof node === "string") {
    const match = node.match(/^\{([\w.]+)\}$/);
    if (!match) return node;
    const parts = match[1].split(".");
    let value = root;
    for (const part of parts) value = value?.[part];
    return typeof value === "string" ? value : node;
  }
  if (Array.isArray(node)) return node.map((n) => resolveRefs(n, root));
  if (node && typeof node === "object") {
    const out = {};
    for (const [k, v] of Object.entries(node)) out[k] = resolveRefs(v, root);
    return out;
  }
  return node;
}

function resolveAllRefs(tree) {
  let current = tree;
  for (let pass = 0; pass < 5; pass++) {
    current = resolveRefs(current, current);
  }
  return current;
}

/**
 * Parses a `linear-gradient(<angle>, <stop>, <stop>, ...)` string into
 * stops usable by `expo-linear-gradient` (colors[] + locations[]).
 * Non-linear gradients (e.g. radial-gradient, used for splash) are kept
 * as raw CSS only — expo-linear-gradient has no radial equivalent.
 */
function parseLinearGradient(css) {
  const match = css.match(/^linear-gradient\(([^,]+),\s*(.+)\)$/);
  if (!match) return null;
  const [, angle, stopsRaw] = match;
  const stopParts = stopsRaw.split(/,(?![^(]*\))/).map((s) => s.trim());
  const stops = stopParts.map((part) => {
    const stopMatch = part.match(/^(#[0-9A-Fa-f]{3,8}|rgba?\([^)]+\))\s*(\d+(?:\.\d+)?%)?$/);
    if (!stopMatch) return { color: part };
    const [, color, locationPct] = stopMatch;
    return locationPct
      ? { color, location: Number.parseFloat(locationPct) / 100 }
      : { color };
  });
  return { angle: angle.trim(), stops };
}

function buildGradients(resolvedGradientMap) {
  const out = {};
  for (const [key, css] of Object.entries(resolvedGradientMap)) {
    const parsed = parseLinearGradient(css);
    out[key] = parsed ? { css, ...parsed } : { css };
  }
  return out;
}

function main() {
  const rawJson = readFileSync(TOKENS_JSON_SRC, "utf8");
  const source = JSON.parse(rawJson);
  const resolved = resolveAllRefs(source);

  const tokens = {
    color: {
      base: resolved.color.base,
      semantic: resolved.color.semantic,
      status: resolved.color.status,
    },
    gradient: buildGradients(resolved.color.gradient),
    typography: resolved.typography,
    spacing: resolved.spacing,
    radius: resolved.radius,
    border: resolved.border,
    shadow: resolved.shadow,
    motion: resolved.motion,
  };

  mkdirSync(OUT_DIR, { recursive: true });

  const tsBody = `${GENERATED_HEADER}
// NOTE: prices are NEVER tokens — they come from pricing_config in the DB
// (see docs/architecture/repository-audit.md §3, §6). Do not add price
// values here.

export const tokens = ${JSON.stringify(tokens, null, 2)} as const;

export type ProtegoTokens = typeof tokens;
`;
  writeFileSync(TOKENS_TS_OUT, tsBody, "utf8");

  const css = readFileSync(TOKENS_CSS_SRC, "utf8");
  const cssBody = `/* AUTO-GENERATED by packages/ui/scripts/sync-tokens.mjs — do not edit by hand.\n   Source: design/PROTEGO mobile safety system design/design/tokens.css */\n${css}`;
  writeFileSync(TOKENS_CSS_OUT, cssBody, "utf8");

  console.log(`Synced tokens:\n  ${TOKENS_TS_OUT}\n  ${TOKENS_CSS_OUT}`);
}

main();
