// AUTO-GENERATED by packages/ui/scripts/sync-tokens.mjs — do not edit by hand.
// Source: design/PROTEGO mobile safety system design/design/tokens.json
// Regenerate: pnpm --filter @protego/ui run tokens:sync

// NOTE: prices are NEVER tokens — they come from pricing_config in the DB
// (see docs/architecture/repository-audit.md §3, §6). Do not add price
// values here.

export const tokens = {
  "color": {
    "base": {
      "ink": "#0C0D0F",
      "graphite": "#15171B",
      "graphite2": "#1C1F24",
      "line": "#2A2E35",
      "lineGold": "#3A341F",
      "void": "#050506",
      "paper": "#F2F3F4",
      "steel": "#9AA0A8",
      "steelDim": "#6B7178",
      "gold": "#C9A227",
      "goldHi": "#E6C868",
      "goldPale": "#EADDA9",
      "goldDim": "rgba(201,162,39,0.14)",
      "goldDim2": "rgba(201,162,39,0.22)",
      "danger": "#E5484D",
      "dangerDim": "rgba(229,72,77,0.12)",
      "ok": "#4CAF7D",
      "okDim": "rgba(76,175,125,0.12)",
      "warn": "#DE8B3F",
      "warnDim": "rgba(222,139,63,0.12)"
    },
    "semantic": {
      "surfaceApp": "#0C0D0F",
      "surfaceCard": "#15171B",
      "surfaceRaised": "#1C1F24",
      "border": "#2A2E35",
      "borderGold": "#3A341F",
      "textPrimary": "#F2F3F4",
      "textSecondary": "#9AA0A8",
      "textTertiary": "#6B7178",
      "textOnGold": "#161307",
      "accent": "#C9A227",
      "accentHi": "#E6C868",
      "accentSoft": "rgba(201,162,39,0.14)"
    },
    "status": {
      "confirmed": "#C9A227",
      "active": "#E6C868",
      "review": "#C9A227",
      "done": "#4CAF7D",
      "sos": "#E5484D",
      "_note": "review = high-risk 'în verificare': ALWAYS calm gold, NEVER danger/red"
    }
  },
  "gradient": {
    "gold": {
      "css": "linear-gradient(135deg, #C9A227 0%, #E6C868 55%, #C9A227 100%)",
      "angle": "135deg",
      "stops": [
        {
          "color": "#C9A227",
          "location": 0
        },
        {
          "color": "#E6C868",
          "location": 0.55
        },
        {
          "color": "#C9A227",
          "location": 1
        }
      ]
    },
    "goldText": {
      "css": "linear-gradient(135deg, #EADDA9, #E6C868 40%, #C9A227)",
      "angle": "135deg",
      "stops": [
        {
          "color": "#EADDA9"
        },
        {
          "color": "#E6C868",
          "location": 0.4
        },
        {
          "color": "#C9A227"
        }
      ]
    },
    "trust": {
      "css": "linear-gradient(135deg, #161207, #14161A 60%)",
      "angle": "135deg",
      "stops": [
        {
          "color": "#161207"
        },
        {
          "color": "#14161A",
          "location": 0.6
        }
      ]
    },
    "quote": {
      "css": "linear-gradient(160deg, #191408, #15171B 70%)",
      "angle": "160deg",
      "stops": [
        {
          "color": "#191408"
        },
        {
          "color": "#15171B",
          "location": 0.7
        }
      ]
    },
    "splash": {
      "css": "radial-gradient(120% 60% at 50% 0%, #181307 0%, #0C0D0F 55%)"
    }
  },
  "typography": {
    "family": {
      "display": "Cinzel",
      "ui": "Manrope",
      "_note": "Cinzel ONLY for the PROTEGO wordmark and agent monograms; Manrope for all UI"
    },
    "size": {
      "micro": 11,
      "caption": 12,
      "small": 13.5,
      "body": 15,
      "title": 17,
      "h3": 20,
      "h2": 24,
      "h1": 28,
      "display": 34,
      "num": 40
    },
    "weight": {
      "regular": 400,
      "medium": 500,
      "semibold": 600,
      "bold": 700,
      "heavy": 800
    },
    "letterSpacing": {
      "wordmark": "0.34em",
      "wordmarkSmall": "0.3em",
      "eyebrow": "0.18em",
      "seg": "0.14em",
      "code": "3px"
    },
    "lineHeight": {
      "tight": 1.25,
      "body": 1.45,
      "note": 1.5
    }
  },
  "spacing": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "gutter": 20,
    "tapMin": 44
  },
  "radius": {
    "sm": 12,
    "md": 14,
    "lg": 16,
    "xl": 18,
    "pill": 999
  },
  "border": {
    "width": 1
  },
  "shadow": {
    "frame": "0 0 80px rgba(0,0,0,0.8)",
    "sos": "0 6px 24px rgba(229,72,77,0.45)",
    "gold": "0 6px 24px rgba(201,162,39,0.25)"
  },
  "motion": {
    "durationPress": "150ms",
    "durationUi": "200ms",
    "durationScreen": "350ms",
    "durationToast": "300ms",
    "easing": "ease",
    "pressScale": 0.985,
    "pulse": "2600ms ease-in-out infinite",
    "_note": "respect prefers-reduced-motion: disable pulse/motion-path, keep fades <= 350ms"
  }
} as const;

export type ProtegoTokens = typeof tokens;
